### ISSUE TITLE
About the sdk license.

### ISSUE THREAD

**Issue by CodingLoverPro** [HMS-Core/hms-audio-editor-demo#10]
Can you please tell me under what license this `'com.huawei.hms: audio-editor-ui: 1.4.0.301'` sdk is provided? Can I add this sdk to my app and distribute it without having any problem?

**Comment by Xuejiao-Shi** [comment]
Are you referring to this [license](https://github.com/HMS-Core/hms-audio-editor-demo#license)? You could directly add the sdk dependency into your project.

**Comment by CodingLoverPro** [comment]
> Are you referring to this [license](https://github.com/HMS-Core/hms-audio-editor-demo#license)?
> 
> > Can I add this sdk to my app and distribute it without having any problem?
> 
> yes, you could directly add the sdk dependency into your project.

Ok, Got it. Thanks for your response.
