### ISSUE TITLE
Can you only extract audio from a video in wav format?.

### ISSUE THREAD

**Issue by Juanjo3299** [HMS-Core/hms-audio-editor-demo#14]
Can you only extract audio from a video in wav format?
Hello.
I have been searching and I can't find the option to extract the audio from video in mp3 or flac format.
*Susuggestion*
There is an excellent [ffmpeg kit](https://github.com/tanersener/ffmpeg-kit) library that you could use to update the version that has this sdk built in.

**Comment by Xuejiao-Shi** [comment]
After the audio is extracted successfully, you can invoke the interface for converting the audio format to convert the WAV format to MP3 or flac format.

https://developer.huawei.com/consumer/en/doc/development/Media-Guides/featured_functions-0000001178963356#section32021910322
