### ISSUE TITLE
Draft Projects

### ISSUE THREAD

**Issue by Juanjo3299** [HMS-Core/hms-audio-editor-demo#16]
Will there be support for saving as a draft project?

In version 1.6.0.301 some methods were removed to be able to save as a draft project, will these methods return in the future?
Currently my application is being built to be able to do it :)

**Comment by Juanjo3299** [comment]
I am currently using the default UI, in version 1.5.301 there was the setSupportDraft method and in the new version it is no longer available, and the draft projects It will allow the user to be able to specifically make their changes without needing to go through all the steps done above, which they would if they could only export their audio.

**Comment by Xuejiao-Shi** [comment]
Thank you for your feedback. Can I confirm the following information:
1. what type of app you are building in? whether **saving as a draft project** is very necessary for your app?
2. Does version 1.5.301 meet the draft function you want, or do you want a complete draft box that supports adding, deleting, modifying, and querying?

**Comment by Xuejiao-Shi** [comment]
hi@[Juanjo3299](https://github.com/Juanjo3299) Thank you for your feedback. The product team they will consider add the Draft Projects capability for the next release version.
