### ISSUE TITLE
音频编辑页面，完成录音后，播放按钮显示播放状态，实际音乐是暂停

### ISSUE THREAD

**Issue by BiZhiChen01** [HMS-Core/hms-audio-editor-demo#3]
[测试环境] MED-AL00 Android10

[步骤] 选歌并应用 -> 展开录音功能栏 -> 开始录音 -> 点击播放icon，播放音乐 -> 暂停录音 -> 打勾收回功能栏

[结果] 播放按钮显示播放状态，但实际上音乐是暂停的

**Comment by Mike-mei** [comment]
请问使用的ui sdk 还是原子能sdk？能否提供录屏复现一下？
