### ISSUE TITLE
添加音效或添加乐段后，播放的声音为杂音

### ISSUE THREAD

**Issue by sss5982** [HMS-Core/hms-audio-editor-demo#8]
目前在 vivo x9 plus 发现，在添加音效或添加乐段页面可以正常播放当前选择的声音，点击使用后，在音频编辑主界面播放的声音为杂音

**Comment by coolleizhu** [comment]
是否可以把音乐内容分享给我们进行分析？

**Comment by coolleizhu** [comment]
可以在
https://developer.huawei.com/consumer/en/support/feedback/#/
提单并附音乐内容。

**Comment by coolleizhu** [comment]
你好，我们在Vivo Z1中进行测试，没有发现有杂音的情况。是否可以录屏（带声音）看一下具体的现象？

**Comment by sss5982** [comment]
https://youtu.be/3IDm0E9uMlY

**Comment by Xuejiao-Shi** [comment]
您好，您的测试手机太老了，建议您在新的机型上Release编译的包试试看

**Comment by sss5982** [comment]
啊，这样呀，是比较老的手机了，新的机型上没问题，谢谢！
